#!/usr/bin/python

import os
import shutil
import glob
ls = os.listdir(".")
files = ['*.deb', '*.tar.zst', '*.tar.xz', '*.rpm', '*.snap', '*.zip']

for x in ls:
    if os.path.isdir(x):
        os.chdir(x)
        try:
            if os.path.isdir('src'):
                print('removing src dir in', os.path.abspath(''))
                shutil.rmtree('src')
            if os.path.isdir('pkg'):
                print('removing pkg dir in', os.path.abspath(''))
                shutil.rmtree('pkg')
            for file in files:
                if glob.glob(file):
                    ffiles = glob.glob(file)
                    for ffile in ffiles:
                        print('removing', ffile, 'in', os.path.abspath(''))
                        os.remove(ffile)
        except OSError as e:
            print("Error: %s " % (e.strerror))
            pass
        os.chdir("..")
