#!/usr/bin/python

import os
import time
import subprocess

ls = os.listdir(".")
for x in ls:
    if os.path.isdir(x):
        os.chdir(x)
        subprocess.call(["git", "pull"])
        os.chdir("..")
    else:
        print("is file ", x)
