#!/usr/bin/python

import os
import time
ls = os.listdir(".")
for x in ls:
    print(x)
    if os.path.isdir(x):
        os.chdir(x)
        os.system('git pull')
        os.chdir("..")
    else:
        print("is file ", x)

